import './bootstrap';
import './fap/main';
import './fap/audio';
import './fap/light';
import './fap/sensor';
import './fap/temperature';
import './fap/admin';
import './fap/doors';
import './fap/smoke';